[project]
name = "vacancy-db"
version = "0.1.0"
description = "Проект по БД"
authors = [
    {name = "Kokc80",email = "kokc@inbox.ru"}
]
license = {text = "none"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
